version: "3.8"

services:
  # PostgreSQL Database
  db:
    image: postgres:15
    container_name: office-mate-db-dev
    environment:
      POSTGRES_DB: officemate
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - office-mate-network

  # FastAPI Backend (Development)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: office-mate-backend-dev
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/officemate
      - DEBUG=True
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - office-mate-network

  # React Frontend (Development)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: office-mate-frontend-dev
    environment:
      - VITE_API_URL=http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - office-mate-network

volumes:
  postgres_data_dev:

networks:
  office-mate-network:
    driver: bridge
